### ISSUE TITLE
Migrating rules to ES6 modules

### ISSUE THREAD

**Issue by fpetrakov** [elirasza/stylelint-stylistic#6]
Hi there, thanks for your work. I want to contribute to your plugin by migrating rules to ES6 modules. The thing is that jest and eslint are not configured properly so I can't do it. Could you please make instructions on how to migrate rules to modules properly without failing tests and making eslint angry or configure them so they don't bother me?

**Comment by elirasza** [comment]
I have just pushed to main and published a new version which changed the project from a static ES5 library to a Typescript (so ES6) built library. You can begin working on the rules if you wish so :)

**Comment by XhmikosR** [comment]
Why switch to ESM? Even Stylelint itself is still using CJS.

**Comment by elirasza** [comment]
Regarding ESM in itself as a coding syntax, I think it allows for better import typing and cleaner approach to modules in general. The only downside I see would be compatibility with other non-ESM modules, but as the project is configured to be compiled to CJS, which is what stylelint will use as a plugin, this particular point becomes irrelevant.

But this can be challenged, what downside would you see ?

**Comment by XhmikosR** [comment]
Indeed, I hadn't seen you switched to TS when I left the comment. I guess it's OK then.
