### ISSUE TITLE
Some rules are not enabled in config compared to before

### ISSUE THREAD

**Issue by XhmikosR** [elirasza/stylelint-stylistic#8]
Hey, @elirasza.

I noticed some rules are not included in the stylelistic/config compared to before.

So far, I noticed:

* declaration-block-single-line-max-declarations
* function-name-case

There might be more, though. If you could go through all of them and add them, that would be perfect.

Thanks!

**Comment by elirasza** [comment]
Hi ! The two rules you mentioned are not deprecated (https://stylelint.io/user-guide/rules/declaration-block-single-line-max-declarations, https://stylelint.io/user-guide/rules/function-name-case), thus are still present in stylelint-config-standard. I did not move them in purpose to avoid maintaining duplicates rules with this package.

**Comment by XhmikosR** [comment]
Oops, my bad then 😅 

I guess they fixed some false positives or something. I'll double-check later, thanks!
